### ISSUE TITLE
GET users/list 500 error

### ISSUE THREAD

**Issue by Syzco** [Capstone-US-Army-PEOSTRI/peostri-lms#65]
http://localhost:5000/api/v1/admin/users/list?filter={"q":"dd"}&range=0&range=24&sort=id&sort=DESC

Throws a 500 error

```  
<-- GET /api/v1/admin/users/list?filter=%7B%22q%22%3A%22dd%22%7D&range=0&range=24&sort=id&sort=DESC
dd
undefined
Non-api error thrown:
TypeError: Cannot read properties of undefined (reading 'type')
    at User.parseQuery (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DBManager.js:68:26)   
    at parseRunSendQuery (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\Router.js:97:24)    
    at C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\Router.js:36:52
    at dispatch (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\koa-compose\index.js:42:32)  
    at C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\@koa\router\lib\router.js:372:16       
    at dispatch (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\koa-compose\index.js:42:32)  
    at C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\koa-compose\index.js:34:12
    at dispatch (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\@koa\router\lib\router.js:377:31)
    at dispatch (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\koa-compose\index.js:42:32)  
    at C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\index.js:70:15
  --> GET /api/v1/admin/users/list?filter=%7B%22q%22%3A%22dd%22%7D&range=0&range=24&sort=id&sort=DESC 500 15ms 33b2ms

**Comment by Syzco** [comment]
Looks to be all queries with filter

```
<-- GET /api/v1/admin/template/modules/list?filter=%7B%22q%22%3A%22Device%20Number%20Request%22%7D&range=0&range=24&sort=id&sort=DESC
Device Number Request
undefined
Non-api error thrown:
TypeError: Cannot read properties of undefined (reading 'type')
    at ModuleTemplate.parseQuery (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DBManager.js:68:26)
    at parseRunSendQuery (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\Router.js:97:24)    
    at C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\Router.js:36:52
    at dispatch (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\koa-compose\index.js:42:32)  
    at C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\@koa\router\lib\router.js:372:16       
    at dispatch (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\koa-compose\index.js:42:32)  
    at C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\koa-compose\index.js:34:12
    at dispatch (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\@koa\router\lib\router.js:377:31)
    at dispatch (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\node_modules\koa-compose\index.js:42:32)  
    at C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\index.js:70:15
  --> GET /api/v1/admin/template/modules/list?filter=%7B%22q%22%3A%22Device%20Number%20Request%22%7D&range=0&range=24&sort=id&sort=DESC 500 14ms 33b
  <-- GET /api/v1/admin/template/modules/list/AKN1cJV4XRkndQU-9NM4qg
  --> GET /api/v1/admin/template/modules/list/AKN1cJV4XRkndQU-9NM4qg 200 23ms 859b
  <-- OPTIONS /api/v1/notifications/list?filter=%7B%22read%22%3Afalse%7D&range=0&range=4&sort=read&sort=ASC
  --> OPTIONS /api/v1/notifications/list?filter=%7B%22read%22%3Afalse%7D&range=0&range=4&sort=read&sort=ASC 204 2ms 
  <-- GET /api/v1/notifications/list?filter=%7B%22read%22%3Afalse%7D&range=0&range=4&sort=read&sort=ASC
false
{"type":"boolean","default":false,"name":"read"}
{ key: 'read', q: false }
  --> GET /api/v1/notifications/list?filter=%7B%22read%22%3Afalse%7D&range=0&range=4&sort=read&sort=ASC 200 17ms 2b
