### ISSUE TITLE
Bad request when waiving modules

### ISSUE THREAD

**Issue by Syzco** [Capstone-US-Army-PEOSTRI/peostri-lms#77]
1. Edit Project
2. Waive Module
3. Add Comment
4. Add File
5. Submit -> Bad Reqest

**Comment by Syzco** [comment]
```
<-- PUT /api/v1/admin/projects/list/BmY4J6mqcTCt8zalJp1o2D
Using default  for users
optional key rank for {"type":"fkey","optional":"true","getIdKeepAsRef":"true","foreignApi":"[object Object]","name":"rank"} dne
key sds is a KEY or ID but DNE
expected key of {"type":"fkey","foreignApi":"[object Object]","optional":"true","freeable":"true","acceptNewDoc":"true","distortOnGet":"(doc) => doc.content","name":"comment"}, got sds, trying bfs
expected key of {"type":"fkey","foreignApi":"[object Object]","optional":"true","acceptNewDoc":"true","distortOnGet":"(doc) => ({\r\n                    src: `api/v1/files/${doc.id}`,\r\n                    title: doc.latest.title,\r\n
     })","name":"file"}, got A8seixQzvTCoWNoEOE-AFp-WeeklyLog-7-1.pdf, trying bfs
ERROR: PUT:/api/v1/admin/projects/list/BmY4J6mqcTCt8zalJp1o2D File.parseGet 400:
  Message: New document unauthorized
  Verbose: New documents [{"src":"DoEj83HQYSTtvrzUtEK4Ea-WeeklyLog-7-1.pdf","title":"WeeklyLog-7-1.pdf","author":"users/EgQLWgHgQzmBrCYeckk4AA"}] not acceptable for type {"type":"fkey","foreignApi":"[object Object]","name":"latest"}
APIError400: New document unauthorized
    at Filedata.IErrorable.error (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\lms\errors.js:63:56)
    at Filedata.parseGet (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DataManager.js:397:32)
    at C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DataManager.js:300:38
    at Filemeta.mapEachField (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DataManager.js:117:42)
    at async Filemeta.verifyAddedDocument (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DataManager.js:255:15)
    at async Filemeta.parseGet (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DataManager.js:355:21)
    at async Waive.mapEachField (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DataManager.js:117:36)
    at async Waive.verifyAddedDocument (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DataManager.js:255:15)
    at async Module.mapEachField (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DataManager.js:113:36)
    at async Module.verifyAddedDocument (C:\Users\brade\Documents\Coursework\COP4935\peostri-lms\backend\build\api\v1\DataManager.js:255:15)
  --> PUT /api/v1/admin/projects/list/BmY4J6mqcTCt8zalJp1o2D 400 98ms 37b
```
